---
app_owncloud_enabled: false
app_owncloud_owncloud_username: "user"
app_owncloud_owncloud_password: "bitnami"
app_owncloud_owncloud_email: "user@example.com"
app_owncloud_owncloud_skip_bootstrap: "no"
app_owncloud_owncloud_host: ""
app_owncloud_owncloud_database_type: "mysql"
app_owncloud_owncloud_database_host: "mariadb"
app_owncloud_owncloud_database_port_number: '3306'
app_owncloud_owncloud_database_name: "bitnami_owncloud"
app_owncloud_owncloud_database_user: "bn_owncloud"
app_owncloud_owncloud_database_password: ""
app_owncloud_allow_empty_password: "no"
app_owncloud_owncloud_smtp_host: ""
app_owncloud_owncloud_smtp_port_number: ''
app_owncloud_owncloud_smtp_user: ""
app_owncloud_owncloud_smtp_password: ""
app_owncloud_suitecrm_smtp_protocol: ""
app_owncloud_php_enable_opcache: ""
app_owncloud_php_expose_php: ""
app_owncloud_php_max_execution_time: ""
app_owncloud_php_max_input_time: ""
app_owncloud_php_max_input_vars: ""
app_owncloud_php_memory_limit: "512M"
app_owncloud_php_post_max_size: "2G"
app_owncloud_php_upload_max_filesize: "2G"
