---
app_pihole_enabled: false
app_pihole_tz: "Europe/Zurich"
app_pihole_webpassword: ""
app_pihole_serverip: ""
app_pihole_admin_email: ""
app_pihole_pihole_dns_: "8.8.8.8"
app_pihole_dnssec: false
app_pihole_dns_bogus_priv: true
app_pihole_dns_fqdn_required: true
app_pihole_rev_server: false
app_pihole_rev_server_domain: ""
app_pihole_rev_server_target: ""
app_pihole_rev_server_cidr: ""
app_pihole_dhcp_active: false
app_pihole_dhcp_start: ""
app_pihole_dhcp_end: ""
app_pihole_dhcp_router: ""
app_pihole_dhcp_leasetime: "24"
app_pihole_pihole_domain: "lan"
app_pihole_dhcp_ipv6: false
app_pihole_dhcp_rapid_commit: false
app_pihole_virtual_host: "$ServerIP"
app_pihole_ipv6: "true"
app_pihole_temperatureunit: "c"
app_pihole_webuiboxedlayout: "boxed"
app_pihole_query_logging: "true"
app_pihole_serveripv6: ""
app_pihole_interface: ""
app_pihole_dnsmasq_listening: ""
app_pihole_web_port: ""
app_pihole_skipgravityonboot: ""
app_pihole_dnsmasq_user: "pihole"
